#this is where the search will be
def search_func():
    print("\n" + "─" * 50)
    print("┌" + "─" * 48 + "┐")
    print("│" + " " * 18 + "iPhone 20" + " " * 19 + "  │")
    print("├" + "─" * 48 + "┤")
    print("│                                                │")
    print("│  What are you searching for?                   │")
    print("│                                                │")
    print("│                                                │")
    print("│                                                │")
    print("│                                                │")
    print("│                                                │")
    print("│                                                │")
    print(" " + "─" * 48 + " ")
    search = input("\n")
    print("\n" + "─" * 50)
    print("┌" + "─" * 48 + "┐")
    print("│" + " " * 18 + "iPhone 20" + " " * 19 + "  │")
    print("├" + "─" * 48 + "┤")
    print("│                                                │")
    print("│  Why are you searching for" , search, "?       │")
    print("│  Touch some grass.                             │")
    print("│                                                │")
    print("│                                                │")
    print("│                                                │")
    print("│                                                │")
    print("│                                                │")
    print(" " + "─" * 48 + " ")

#search_func()